##################################################################################################
# dataset root
DATASET_ROOT: 'shapenet_plain'
DATASET_CATES: ['02958343'] # '02691156',,'02958343']
# choose dataset
DATASET: 'p2m_eval_2way_dataset'
PROPORTION: 1.0
#DATASET: 'nips_dataset'
#PROPORTION: 0.00025
DATASET_INDEX: ['resource/data/index/p2m_chair_test.json']
##################################################################################################
MODES: ['test']
MODEL: 'pixel2mesh_mveval'

GPU: [0]
BATCHSIZE: 2
DATALOADER_WORKERS: 16
EPOCH_TOTAL: 1

LR: 0.0

LOG_DIR: 'eccv-comparison-p2mpp-chair-plain'
LOGGER: 'logger_s1'
LOGGER_SELECT: ['metric','image','model','xls']
MODEL_SAVE_PER_N_EPOCH: 10
VIS_PER_N_EPOCH: 1
VIS_PER_N_BATCH: 10
VIS_ONE_PER_BATCH: True
VIS_TRAIN_PER_BATCH: 20

BACKUP_FILES: ['core/toolbox/evaluation.py']