##################################################################################################
# dataset root
DATASET_ROOT: 'shapenet_plain'
DATASET_CATES: ['02958343']
# choose dataset
DATASET: 'mv5_correspondence_dataset'
PROPORTION: 1.0
#DATASET: 'nips_dataset'
#PROPORTION: 0.00025
DATASET_INDEX: ['resource/data/index/shapenet_plain_plane_train.json',
                'resource/data/index/shapenet_plain_plane_test.json']
##################################################################################################
MODES: ['test']
MODEL: 'xnocs_mv_mveval'

GPU: [0]
BATCHSIZE: 1
DATALOADER_WORKERS: 4
EPOCH_TOTAL: 1

LR: 0.0

LOG_DIR: 'eccv-comparison-xnocs-mv-plane-plain'
LOGGER: 'logger_s1'
LOGGER_SELECT: ['metric','image','model','xls']
MODEL_SAVE_PER_N_EPOCH: 1
VIS_PER_N_EPOCH: 1
VIS_PER_N_BATCH: 20
VIS_ONE_PER_BATCH: True
VIS_TRAIN_PER_BATCH: 30

#RESUME: True
#RESUME_EPOCH_ID: 400

RESUME: False
MODEL_INIT_PATH: ['final_log/xnocs-weight/PermEq-BS_1-Arch_SetSegNetSkipPermEq-airplanes-LR_0.000100-Seed_0_PeeledColor_WithMask-SetSize_05_Fixed-GPU_06_1571995432516194.tar']

BACKUP_FILES: ['core/net_bank/vgg.py',
               'core/net_bank/uv_amp_mlp.py',
               'core/net_bank/loss.py']