##################################################################################################
# dataset root
DATASET_ROOT: 'shapenet_plain'
DATASET_CATES: ['02691156'] #'02691156',,'02958343']
# choose dataset
DATASET: 'nips_dataset_noise'
PROPORTION: 1.0
DATASET_INDEX: ['resource/data/index/shapenet_plain_plane_train.json',
                'resource/data/index/shapenet_plain_plane_test.json']
##################################################################################################
MODES: ['train','test']
MODEL: 'image2surf_sv'

GPU: [0,1]
BATCHSIZE: 16
DATALOADER_WORKERS: 6
EPOCH_TOTAL: 20000

LR: 3e-5
OPTI_DECAY_RATE: 0.5
OPTI_DECAY_INTERVAL: 100
OPTI_DECAY_MIN: 1e-8

LOG_DIR: 'eccv-image2surf-sv-plane-plain'
LOGGER: 'logger_s1'
LOGGER_SELECT: ['metric','image','model','xls']
MODEL_SAVE_PER_N_EPOCH: 3
VIS_PER_N_EPOCH: 1
VIS_PER_N_BATCH: 60
VIS_ONE_PER_BATCH: True
VIS_TRAIN_PER_BATCH: 120

#RESUME: True
#RESUME_EPOCH_ID: 400

RESUME: False
MODEL_INIT_PATH: ['log/eccv-xnocsinit-sv-noise-plane-plain-b16/model/epoch_25.model']

BACKUP_FILES: ['core/net_bank/vgg.py',
               'core/net_bank/uv_amp_mlp.py',
               'core/net_bank/loss.py']