##################################################################################################
# dataset root
DATASET_ROOT: 'shapenet_plain'
DATASET_CATES: ['02958343'] # '02691156',,'02958343']
# choose dataset
DATASET: 'mv5_correspondence_x_dataset_noise'
PROPORTION: 1.0
DATASET_INDEX: ['resource/data/index/shapenet_plain_car_train.json',
                'resource/data/index/shapenet_plain_car_test.json']
##################################################################################################
MODES: ['train','test']
MODEL: 'pix2surf_mv_x'

GPU: [0,1]
BATCHSIZE: 4
DATALOADER_WORKERS: 6
EPOCH_TOTAL: 20000

LR: 1e-4
OPTI_DECAY_RATE: 0.5
OPTI_DECAY_INTERVAL: 50
OPTI_DECAY_MIN: 1e-8

LOG_DIR: 'eccv-pix2surf-mv-x-car-plain'
LOGGER: 'logger_s1'
LOGGER_SELECT: ['metric','image','model','xls']
MODEL_SAVE_PER_N_EPOCH: 3
VIS_PER_N_EPOCH: 1
VIS_PER_N_BATCH: 50
VIS_ONE_PER_BATCH: True
VIS_TRAIN_PER_BATCH: 200

#RESUME: True
#RESUME_EPOCH_ID: 400

RESUME: False
MODEL_INIT_PATH: ['log/eccv-pix2surf-sv-x-car-plain/model/epoch_30.model']


BACKUP_FILES: ['core/net_bank/vgg.py',
               'core/net_bank/uv_amp_mlp.py',
               'core/net_bank/loss.py']