##################################################################################################
# dataset root
DATASET_ROOT: 'shapenet_plain'
DATASET_CATES: ['03001627'] #'02691156',,'02958343']
# choose dataset
DATASET: 'mv5_correspondence_dataset'
PROPORTION: 1.0
DATASET_INDEX: ['resource/data/index/shapenet_plain_chair_train.json',
                'resource/data/index/shapenet_plain_chair_test.json']
##################################################################################################
MODES: ['test']
MODEL: 'pix2surf_sv_render_v4_chair_siren'

GPU: [0]
BATCHSIZE: 2
DATALOADER_WORKERS: 4
EPOCH_TOTAL: 1

LR: 0.0

LOG_DIR: 'eccv-render-pix2surf-sv5-chair-siren'
LOGGER: 'logger_s1'
LOGGER_SELECT: ['metric','image','model','xls']
MODEL_SAVE_PER_N_EPOCH: 1
VIS_PER_N_EPOCH: 1
VIS_PER_N_BATCH: 1
VIS_ONE_PER_BATCH: False
VIS_TRAIN_PER_BATCH: 30

#RESUME: True
#RESUME_EPOCH_ID: 400

RESUME: False
MODEL_INIT_PATH: ['log/siren_pix2surf_sv_chair_plain_epoch_30.model']

BACKUP_FILES: ['core/net_bank/vgg.py',
               'core/net_bank/uv_amp_mlp.py',
               'core/net_bank/loss.py',
               'core/toolbox/evaluation.py']