##################################################################################################
# dataset root
DATASET_ROOT: 'pix2surf_viz'
DATASET_CATES: ['chair']
# choose dataset
DATASET: 'mv5_correspondence_dataset'
PROPORTION: 1.0
#DATASET: 'nips_dataset'
#PROPORTION: 0.00025
DATASET_INDEX: ['resource/data/index/pix2surf_viz_chair_test.json']
##################################################################################################
MODES: ['test']
MODEL: 'pix2surf_sv_render_v4_chair'

GPU: [0]
BATCHSIZE: 2
DATALOADER_WORKERS: 4
EPOCH_TOTAL: 1

LR: 0.0

LOG_DIR: 'eccv-render-pix2surf-sv5-chair-viz'
LOGGER: 'logger_s1'
LOGGER_SELECT: ['metric','image','model','xls','obj']
MODEL_SAVE_PER_N_EPOCH: 1
VIS_PER_N_EPOCH: 1
VIS_PER_N_BATCH: 1
VIS_ONE_PER_BATCH: False
VIS_TRAIN_PER_BATCH: 30

#RESUME: True
#RESUME_EPOCH_ID: 400

RESUME: False
MODEL_INIT_PATH: ['final_log/SUP/nocsmlp3_chair_e13.model']

BACKUP_FILES: ['core/net_bank/vgg.py',
               'core/net_bank/uv_amp_mlp.py',
               'core/net_bank/loss.py',
               'core/toolbox/evaluation.py']