##################################################################################################
# dataset roota
DATASET_ROOT: 'nocs_nips'
DATASET_CATES: ['02958343']
# choose dataset
DATASET: 'fit_v0_dataset'
##################################################################################################
MODES: ['test']

MODEL: 'probe_fit_v0'

GPU: [0]
BATCHSIZE: 1
DATALOADER_WORKERS: 1
EPOCH_TOTAL: 1

LR: 1e-4
OPTI_DECAY_RATE: 0.7
OPTI_DECAY_INTERVAL: 36
OPTI_DECAY_MIN: 1e-8

LOG_DIR: 'fit-v0.2-1000-1e-4'
LOGGER: 'logger_force'

MODEL_SAVE_PER_N_EPOCH: 20
VIS_ONE_PER_BATCH: True