# For new logger and mini dataset
##################################################################################################
# dataset root
DATASET_ROOT: 'nocs_nips_mini'
DATASET_CATES: ['02691156']#,'02958343','02958343']
# choose dataset
DATASET: 'fit_v0_dataset'
##################################################################################################
MODES: ['test']
MODEL: 'probe_fit_v1'

GPU: [0]
BATCHSIZE: 1
DATALOADER_WORKERS: 1
EPOCH_TOTAL: 10

LR: 1e-4
OPTI_DECAY_RATE: 0.7
OPTI_DECAY_INTERVAL: 36
OPTI_DECAY_MIN: 1e-8

LOG_DIR: 'fit-v1.3.2-1000-1e4'
LOGGER: 'logger_s1'
LOGGER_SELECT: ['metric','image','pc']

VIS_ONE_PER_BATCH: True
VIS_TRAIN_PER_BATCH: 1
BACKUP_FILES: ['core/net_bank/probes.py']