# NOTE, THIS CONFIG IS FOR LOCAL RUNNING, NEED TO BE SCALED UP
# (INCREASE BATCH SIZE,USE MULTI-GPU, DECREASE VIS FREQUENCY....) IF DO REAL TRAINING

##################################################################################################
# dataset root
DATASET_ROOT: 'hand_rig_dataset_v3'
DATASET_CATES: ['hand'] #'02691156',,'02958343','02958343']
# choose dataset
DATASET: 'hand_joint_uv_dataset'
DATASET_INDEX: ['resource/data/index/hand_pnjuv_local_train.json',
                'resource/data/index/hand_pnjuv_local_val.json']
##################################################################################################
MODES: ['train']
MODEL: 'hand_v4_p1'

GPU: [0]
BATCHSIZE: 1p
DATALOADER_WORKERS: 6
EPOCH_TOTAL: 20000

LR: 1e-5
OPTI_DECAY_RATE: 0.5
OPTI_DECAY_INTERVAL: 200
OPTI_DECAY_MIN: 1e-8

LOG_DIR: 'hand-v4-phase1'
LOGGER: 'logger_s1'
LOGGER_SELECT: ['metric','image','model','xls']
MODEL_SAVE_PER_N_EPOCH: 3
VIS_PER_N_EPOCH: 2
VIS_PER_N_BATCH: 1
VIS_ONE_PER_BATCH: True
VIS_TRAIN_PER_BATCH: 2

#RESUME: True
#RESUME_EPOCH_ID: 8

#RESUME: False
#MODEL_INIT_PATH: ['log/hand_v4p1_epoch_10.model']

BACKUP_FILES: ['core/net_bank/vgg.py',
               'core/net_bank/uv_amp_mlp.py',
               'core/net_bank/loss.py']