##################################################################################################
# dataset root
DATASET_ROOT: 'hand_rig_dataset_v3'
DATASET_CATES: ['hand'] #'02691156',,'02958343','02958343']
# choose dataset
DATASET: 'hand_joint_uv_dataset2'
PROPORTION: 0.01
DATASET_INDEX: ['resource/data/index/hand_pnjuv_train.json',
                'resource/data/index/hand_pnjuv_val.json']
##################################################################################################
MODES: ['train','val']
MODEL: 'hand_v4_1_p1'

GPU: [0,1]
BATCHSIZE: 12
DATALOADER_WORKERS: 6
EPOCH_TOTAL: 2000

LR: 1e-4
OPTI_DECAY_RATE: 0.5
OPTI_DECAY_INTERVAL: 100
OPTI_DECAY_MIN: 1e-8

LOG_DIR: 'hand-v4.1-p1'
LOGGER: 'logger_s1'
LOGGER_SELECT: ['metric','image','model','xls']
MODEL_SAVE_PER_N_EPOCH: 10
VIS_PER_N_EPOCH: 1
VIS_PER_N_BATCH: 40
VIS_ONE_PER_BATCH: True
VIS_TRAIN_PER_BATCH: 100

#RESUME: True
#RESUME_EPOCH_ID: 8

#RESUME: False
#MODEL_INIT_PATH: ['log/hand_nocsreg_epoch_31.model']
#MODEL_INIT_PATH: ['log/hand_v4p1_epoch_10.model']
#MODEL_INIT_PATH: ['log/sv-v1-cell-p1/model/epoch_30.model']

BACKUP_FILES: ['core/net_bank/uresnet.py',
               'core/net_bank/uv_amp_mlp.py',
               'core/net_bank/loss.py']