##################################################################################################
# dataset root
DATASET_ROOT: 'hand_rig_dataset_v3'
DATASET_CATES: ['hand']
# choose dataset
DATASET: 'hand_joint_dataset'
PROPORTION: 1.0
DATASET_INDEX: ['resource/data/index/hand_pn_train.json','resource/data/index/hand_pn_val.json']
##################################################################################################
MODES: ['train','val']
MODEL: 'vnocs_v1'

GPU: [0,1]
BATCHSIZE: 10
DATALOADER_WORKERS: 3
EPOCH_TOTAL: 200

LR: 1e-4
OPTI_DECAY_RATE: 0.5
OPTI_DECAY_INTERVAL: 200
OPTI_DECAY_MIN: 1e-8

LOG_DIR: 'vnocs-v1-postprocessing'
LOGGER: 'logger_s1'
LOGGER_SELECT: ['metric','image','model','xls']
MODEL_SAVE_PER_N_EPOCH: 3
VIS_PER_N_EPOCH: 100
VIS_PER_N_BATCH: 1
VIS_ONE_PER_BATCH: True
VIS_TRAIN_PER_BATCH: 200

#RESUME: True
#RESUME_EPOCH_ID: 38

RESUME: False
MODEL_INIT_PATH: ['log/hand_nocsreg_epoch_31.model']

BACKUP_FILES: ['core/net_bank/pointnet.py',
               'core/net_bank/uv_amp_mlp.py',
               'core/net_bank/loss.py',
               'resource/data/index/hand_pn_train.json',
               'resource/data/index/hand_pn_val.json']