##################################################################################################
# dataset root
DATASET_ROOT: 'hand_rig_dataset_v3'
DATASET_CATES: ['hand'] #'02691156',,'02958343']
# choose dataset
DATASET: 'hand_joint_dataset'
#DATASET: 'nocs_atlas_dataset'
PROPORTION: 1.0
DATASET_INDEX: ['resource/data/index/hand_pn_train.json','resource/data/index/hand_pn_val.json']
##################################################################################################
MODES: ['val']
MODEL: 'vnocs_v0_baseline'

GPU: [0]
BATCHSIZE: 2
DATALOADER_WORKERS: 4
EPOCH_TOTAL: 2

LR: 1e-5
OPTI_DECAY_RATE: 0.5
OPTI_DECAY_INTERVAL: 250
OPTI_DECAY_MIN: 1e-8

LOG_DIR: 'vnocs-v0-baseline-eval'
LOGGER: 'logger_s1'
LOGGER_SELECT: ['metric','image','model','xls']
MODEL_SAVE_PER_N_EPOCH: 1
VIS_PER_N_EPOCH: 1
VIS_PER_N_BATCH: 200
VIS_ONE_PER_BATCH: True
VIS_TRAIN_PER_BATCH: 200

#RESUME: True
#RESUME_EPOCH_ID: 38

RESUME: False
MODEL_INIT_PATH: ['log/vnocs_v0_baseline_epoch_95.model']

BACKUP_FILES: ['core/net_bank/pointnet.py',
               'core/net_bank/uv_amp_mlp.py',
               'core/net_bank/loss.py',
               'resource/data/index/hand_pn_train.json',
               'resource/data/index/hand_pn_val.json']