##################################################################################################
# dataset root
DATASET_ROOT: 'nocs_nips_all_dgx'
DATASET_CATES: ['02958343'] #'02691156',,'02958343']
# choose dataset
DATASET: 'atlas_mv_dataset'
DATASET_INDEX: ['resource/data/index/car_2048_train.json',
                'resource/data/index/car_2048_vali.json',
                'resource/data/index/car_2048_test.json']
##################################################################################################
MODES: ['train','vali']
MODEL: 'atlasnet_mvr_sph'

GPU: [0,1,2,3]
BATCHSIZE: 32
DATALOADER_WORKERS: 16
EPOCH_TOTAL: 1000

LR: 3e-4
OPTI_DECAY_RATE: 0.8
OPTI_DECAY_INTERVAL: 50
OPTI_DECAY_MIN: 1e-10

LOG_DIR: 'base-AtlasNet-svr-sph'
LOGGER: 'logger_s1'
LOGGER_SELECT: ['metric','image','model']
MODEL_SAVE_PER_N_EPOCH: 10
VIS_PER_N_BATCH: 5
VIS_ONE_PER_BATCH: True
VIS_TRAIN_PER_BATCH: 40

#RESUME: False
#MODEL_INIT_PATH: ['log/cam-v4.5-p2-dgx/model/epoch_400.model']


#RESUME: True
#RESUME_EPOCH_ID: 12

BACKUP_FILES: ['core/net_bank/hyper_column_net.py',
               'core/net_bank/nox_mlp.py',
               'core/net_bank/loss.py',
               'resource/data/index/car_2048_train.json',
               'resource/data/index/car_2048_vali.json',
               'resource/data/index/car_2048_test.json']