##################################################################################################
# dataset root
DATASET_ROOT: 'nocs_nips_all_net'
DATASET_CATES: ['02958343'] #'02691156',,'02958343']
# choose dataset
DATASET: 'nox_mv2_dataset'
DATASET_INDEX: ['resource/data/index/car_2048_train.json',
                'resource/data/index/car_2048_vali.json',
                'resource/data/index/car_2048_test.json']
##################################################################################################
MODES: ['vali']
MODEL: 'cam_v4_2_eval'

GPU: [2,3]
BATCHSIZE:
DATALOADER_WORKERS: 8
EPOCH_TOTAL: 2

LR: 3e-4
OPTI_DECAY_RATE: 0.8
OPTI_DECAY_INTERVAL: 30
OPTI_DECAY_MIN: 1e-6

LOG_DIR: 'cam-v4.2-eval-p3'
LOGGER: 'logger_s1'
LOGGER_SELECT: ['metric','image','model']
MODEL_SAVE_PER_N_EPOCH: 1
VIS_PER_N_BATCH: 1
VIS_ONE_PER_BATCH: False
VIS_TRAIN_PER_BATCH: 40

RESUME: False
MODEL_INIT_PATH: ['log/cam-v4.2-p3/model/epoch_270.model']

BACKUP_FILES: ['core/net_bank/uresnet.py',
               'core/net_bank/nocs_surface_mlps.py',
               'core/net_bank/loss.py',
               'resource/data/index/car_2048_train.json',
               'resource/data/index/car_2048_vali.json',
               'resource/data/index/car_2048_test.json']