##################################################################################################
# dataset root
DATASET_ROOT: 'nocs_nips_all_dgx'
DATASET_CATES: ['02958343'] #'02691156',,'02958343']
# choose dataset
DATASET: 'atlas_mv_overfit_dataset'
DATASET_INDEX: ['resource/data/index/car_2048_train.json',
                'resource/data/index/car_2048_vali.json',
                'resource/data/index/car_2048_test.json']
##################################################################################################
MODES: ['train']
MODEL: 'cellnet_v6_9'

GPU: [0,1,2,3]
BATCHSIZE: 64
DATALOADER_WORKERS: 4
EPOCH_TOTAL: 1000

LR: 1e-4
OPTI_DECAY_RATE: 0.5
OPTI_DECAY_INTERVAL: 100
OPTI_DECAY_MIN: 1e-8

LOG_DIR: 'cellnet-v6.9-of'
LOGGER: 'logger_s1'
LOGGER_SELECT: ['metric','image','model']
MODEL_SAVE_PER_N_EPOCH: 6
VIS_PER_N_BATCH: 1
VIS_ONE_PER_BATCH: True
VIS_TRAIN_PER_BATCH: 1

#RESUME: True
#RESUME_EPOCH_ID: 22

BACKUP_FILES: ['core/net_bank/pointnet.py',
               'core/net_bank/nox_mlp.py',
               'core/net_bank/loss.py',
               'resource/data/index/car_2048_train.json',
               'resource/data/index/car_2048_vali.json',
               'resource/data/index/car_2048_test.json']