##################################################################################################
# dataset root
DATASET_ROOT: 'nocs_nips_all_dgx'
DATASET_CATES: ['02958343'] #'02691156',,'02958343']
# choose dataset
DATASET: 'nocs_mv_new_dataset'
DATASET_INDEX: ['resource/data/index/car_sdf_train.json',
                'resource/data/index/car_sdf_vali.json',
                'resource/data/index/car_sdf_test.json']
##################################################################################################
MODES: ['train','vali']
MODEL: 'cellnet_v6_15'

GPU: [0,1,2,3]
BATCHSIZE:  16
DATALOADER_WORKERS: 20
EPOCH_TOTAL: 2000

LR: 3e-4
OPTI_DECAY_RATE: 0.8
OPTI_DECAY_INTERVAL: 100
OPTI_DECAY_MIN: 1e-8

LOG_DIR: 'cellnet-v6.15-sgmd'
LOGGER: 'logger_s1'
LOGGER_SELECT: ['metric','image','model']
MODEL_SAVE_PER_N_EPOCH: 3
VIS_PER_N_BATCH: 4
VIS_ONE_PER_BATCH: True
VIS_TRAIN_PER_BATCH: 4

#RESUME: False
#MODEL_INIT_PATH: ['log/SERVER-DOWNLOAD/epoch_48.model']


#RESUME: True
#RESUME_EPOCH_ID: 1

BACKUP_FILES: ['core/net_bank/nox_mlp.py',
               'core/net_bank/nsc_net_new.py',
               'core/net_bank/nsc_fusion.py',
               'core/net_bank/loss.py',
               'resource/data/index/car_sdf_train.json',
               'resource/data/index/car_sdf_vali.json',
               'resource/data/index/car_sdf_test.json']