##################################################################################################
# dataset root
DATASET_ROOT: 'nocs_nips_all'
DATASET_CATES: ['02958343'] #'02691156',,'02958343']
# choose dataset
#DATASET: 'nox_divid_dataset'
#DATASET_INDEX: ['resource/data/index/car_2048_train.json',
#                'resource/data/index/car_2048_vali.json',
#                'resource/data/index/car_2048_test.json']
DATASET: 'sdf_nox_dataset'
DATASET_INDEX: ['resource/data/index/car_sdf_train.json',
                'resource/data/index/car_sdf_vali.json',
                'resource/data/index/car_sdf_test.json']
##################################################################################################
MODES: ['train','vali']
MODEL: 'force_v6_13'

GPU: [0,1,2,3]
BATCHSIZE: 16
DATALOADER_WORKERS: 20
EPOCH_TOTAL: 1000

LR: 3e-4
OPTI_DECAY_RATE: 0.5
OPTI_DECAY_INTERVAL: 32
OPTI_DECAY_MIN: 1e-8

LOG_DIR: 'force-v6.13-new2'
LOGGER: 'logger_s1'
LOGGER_SELECT: ['metric','image','model']
MODEL_SAVE_PER_N_EPOCH: 1
VIS_PER_N_BATCH: 5
VIS_ONE_PER_BATCH: True
VIS_TRAIN_PER_BATCH: 10

#RESUME: True
#RESUME_EPOCH_ID: 22

RESUME: False
MODEL_INIT_PATH: ['log/force-v6.13-new1/model/epoch_20.model']

BACKUP_FILES: ['core/net_bank/uresnet.py',
               'core/net_bank/nsc_net_new.py',
               'core/net_bank/nox_mlp.py',
               'core/net_bank/loss.py',
               'resource/data/index/car_2048_train.json',
               'resource/data/index/car_2048_vali.json',
               'resource/data/index/car_2048_test.json']