##################################################################################################
# dataset root
DATASET_ROOT: 'nocs_nips_all_net'
DATASET_CATES: ['02958343'] #'02691156',,'02958343']
# choose dataset
DATASET: 'nox_mv_origin_dataset'
DATASET_INDEX: ['resource/data/index/car_2048_train.json',
                'resource/data/index/car_2048_vali.json',
                'resource/data/index/car_2048_test.json']
##################################################################################################
MODES: ['vali','test']
MODEL: 'force_v6_12_eval'

GPU: [2,3]
BATCHSIZE: 4
DATALOADER_WORKERS: 20
EPOCH_TOTAL: 2

LR: 3e-4
OPTI_DECAY_RATE: 0.5
OPTI_DECAY_INTERVAL: 64
OPTI_DECAY_MIN: 1e-8

LOG_DIR: 'fish-v6.12-eval'
LOGGER: 'logger_s1'
LOGGER_SELECT: ['metric','image','model']
MODEL_SAVE_PER_N_EPOCH: 1
VIS_PER_N_BATCH: 3
VIS_ONE_PER_BATCH: False
VIS_TRAIN_PER_BATCH: 3

#RESUME: True
#RESUME_EPOCH_ID: 2

RESUME: False
MODEL_INIT_PATH: ['log/fish-v6.12-p2/model/epoch_139.model']

BACKUP_FILES: ['core/net_bank/nsc_fusion.py',
               'core/net_bank/nsc_net_new.py',
               'core/net_bank/nox_mlp.py',
               'core/net_bank/loss.py',
               'resource/data/index/car_2048_train.json',
               'resource/data/index/car_2048_vali.json',
               'resource/data/index/car_2048_test.json']