##################################################################################################
# dataset root
DATASET_ROOT: 'nocs_nips_all_net'
DATASET_CATES: ['02958343'] #'02691156',,'02958343']
# choose dataset
DATASET: 'nox_dense_dataset'
DATASET_INDEX: ['resource/data/index/car_2048_train.json',
                'resource/data/index/car_2048_vali.json',
                'resource/data/index/car_2048_test.json']
##################################################################################################
MODES: ['vali','test']
MODEL: 'hyper_column_v0_0_eval'

GPU: [0,1]
BATCHSIZE: 6
DATALOADER_WORKERS: 6
EPOCH_TOTAL: 2

LR: 3e-4
OPTI_DECAY_RATE: 0.8
OPTI_DECAY_INTERVAL: 30
OPTI_DECAY_MIN: 1e-6

LOG_DIR: 'hyper-column-v0.0-eval'
LOGGER: 'logger_s1'
LOGGER_SELECT: ['metric','image','model']
MODEL_SAVE_PER_N_EPOCH: 1
VIS_PER_N_BATCH: 5
VIS_ONE_PER_BATCH: False
VIS_TRAIN_PER_BATCH: 1

#RESUME: True
#RESUME_EPOCH_ID: 12

RESUME: False
MODEL_INIT_PATH: ['log/hyper-column-v0.0/model/epoch_50.model']

BACKUP_FILES: ['core/net_bank/hyper_column_net.py',
               'core/net_bank/nox_mlp.py',
               'core/net_bank/loss.py',
               'resource/data/index/car_2048_train.json',
               'resource/data/index/car_2048_vali.json',
               'resource/data/index/car_2048_test.json']