##################################################################################################
# dataset root
DATASET_ROOT: 'nocs_nips_all'
DATASET_CATES: ['03001627'] #'02691156',,'02958343']
# choose dataset
DATASET: 'nips_dataset'
PROPORTION: 0.025
DATASET_INDEX: ['resource/data/index/chair_2048_train.json',
                'resource/data/index/chair_2048_vali.json',
                'resource/data/index/chair_2048_test.json']
##################################################################################################
MODES: ['train']
MODEL: 'mlp_mix_v8_7_6_eval'

GPU: [0,1]
BATCHSIZE: 4
DATALOADER_WORKERS: 8
EPOCH_TOTAL: 2

LR: 3e-5
OPTI_DECAY_RATE: 0.5
OPTI_DECAY_INTERVAL: 100
OPTI_DECAY_MIN: 1e-8

LOG_DIR: 'mlp-mix-v8.7.6-chair-of-eval'
LOGGER: 'logger_s1'
LOGGER_SELECT: ['metric','image','model','xls']
MODEL_SAVE_PER_N_EPOCH: 1
VIS_PER_N_BATCH: 1
VIS_ONE_PER_BATCH: False
VIS_TRAIN_PER_BATCH: 1

#RESUME: True
#RESUME_EPOCH_ID: 22

RESUME: False
#MODEL_INIT_PATH: ['log/nip_s-baseline-chair/model/epoch_30.model']
MODEL_INIT_PATH: ['log/mlp-mix-v8.7.6-chair-of/model/epoch_95.model']

BACKUP_FILES: ['core/net_bank/vgg.py',
               'core/net_bank/nox_mlp.py',
               'core/net_bank/loss.py',
               'resource/data/index/chair_2048_train.json',
               'resource/data/index/chair_2048_vali.json',
               'resource/data/index/chair_2048_test.json']