##################################################################################################
# dataset root
DATASET_ROOT: 'nocs_nips_all_net'
DATASET_CATES: ['02958343'] #'02691156',,'02958343']
# choose dataset
DATASET: 'nox_divide_overfit_dataset'
DATASET_INDEX: ['resource/data/index/car_2048_train.json',
                'resource/data/index/car_2048_vali.json',
                'resource/data/index/car_2048_test.json']
##################################################################################################
MODES: ['train']
MODEL: 'multi_v6_2'

GPU: [0,1,2,3]
BATCHSIZE: 16
DATALOADER_WORKERS: 16
EPOCH_TOTAL: 1000

LR: 3e-4
OPTI_DECAY_RATE: 0.7
OPTI_DECAY_INTERVAL: 10
OPTI_DECAY_MIN: 1e-8

LOG_DIR: 'multi-v6.2-overfit1'
LOGGER: 'logger_s1'
LOGGER_SELECT: ['metric','image','model']
MODEL_SAVE_PER_N_EPOCH: 10
VIS_PER_N_BATCH: 5
VIS_ONE_PER_BATCH: True
VIS_TRAIN_PER_BATCH: 5

#RESUME: True
#RESUME_EPOCH_ID: 12

BACKUP_FILES: ['core/net_bank/uresnet.py',
               'core/net_bank/nsc_net_new.py',
               'core/net_bank/loss.py',
               'resource/data/index/car_2048_train.json',
               'resource/data/index/car_2048_vali.json',
               'resource/data/index/car_2048_test.json']