##################################################################################################
# dataset root
DATASET_ROOT: 'nocs_nips_all_net'
DATASET_CATES: ['02958343'] #'02691156',,'02958343']
# choose dataset
DATASET: 'nips_dataset2'
DATASET_INDEX: ['resource/data/index/car_2048_train.json',
                'resource/data/index/car_2048_vali.json',
                'resource/data/index/car_2048_test.json']
##################################################################################################
MODES: ['vali']
MODEL: 'nips_uresnet_eval'

GPU: [1]
BATCHSIZE: 8
DATALOADER_WORKERS: 20
EPOCH_TOTAL: 2

LR: 3e-4
OPTI_DECAY_RATE: 0.5
OPTI_DECAY_INTERVAL: 32
OPTI_DECAY_MIN: 1e-8

LOG_DIR: 'ures-baseline'
LOGGER: 'logger_s1'
LOGGER_SELECT: ['metric','image','model','xls']
MODEL_SAVE_PER_N_EPOCH: 1
VIS_PER_N_BATCH: 1
VIS_ONE_PER_BATCH: False
VIS_TRAIN_PER_BATCH: 15

#RESUME: True
#RESUME_EPOCH_ID: 22

RESUME: False
MODEL_INIT_PATH: ['log/SERVER-DOWNLOAD/uresnet.model']

BACKUP_FILES: ['core/net_bank/nips_nox_network',
               'core/net_bank/loss.py',
               'resource/data/index/car_sdf_train.json',
               'resource/data/index/car_sdf_vali.json',
               'resource/data/index/car_sdf_test.json']