##################################################################################################
# dataset root
DATASET_ROOT: 'nocs_nips_all_dgx'
DATASET_CATES: ['02958343'] #'02691156',,'02958343']
# choose dataset
DATASET: 'sdf_nox_dataset'
DATASET_INDEX: ['resource/data/index/car_sdf_train.json',
                'resource/data/index/car_sdf_vali.json',
                'resource/data/index/car_sdf_test.json']
##################################################################################################
MODES: ['train','vali']
MODEL: 'nocsdf_v7_1'

GPU: [0,1,2,3]
BATCHSIZE:  16
DATALOADER_WORKERS: 20
EPOCH_TOTAL: 2000

LR: 3e-4
OPTI_DECAY_RATE: 0.8
OPTI_DECAY_INTERVAL: 100
OPTI_DECAY_MIN: 1e-8

LOG_DIR: 'nocsdf-v7.1-p2'
LOGGER: 'logger_s1'
LOGGER_SELECT: ['metric','image','model']
MODEL_SAVE_PER_N_EPOCH: 3
VIS_PER_N_BATCH: 5
VIS_ONE_PER_BATCH: True
VIS_TRAIN_PER_BATCH: 10

RESUME: False
MODEL_INIT_PATH: ['log/nocsdf-v7.1-p1/model/epoch_27.model']


#RESUME: True
#RESUME_EPOCH_ID: 55

BACKUP_FILES: ['core/net_bank/deepsdf_net.py',
               'core/net_bank/uresnet.py',
               'core/net_bank/loss.py',
               'resource/data/index/car_sdf_train.json',
               'resource/data/index/car_sdf_vali.json',
               'resource/data/index/car_sdf_test.json']