##################################################################################################
# dataset root
DATASET_ROOT: 'nocs_nips_all_dgx'
DATASET_CATES: ['02958343'] #'02691156',,'02958343']
# choose dataset
DATASET: 'nox_mv_origin_overfit_dataset'
DATASET_INDEX: ['resource/data/index/car_2048_train.json',
                'resource/data/index/car_2048_vali.json',
                'resource/data/index/car_2048_test.json']
##################################################################################################
MODES: ['train']
MODEL: 'nsc_v3_16'

GPU: [0,1,2,3]
BATCHSIZE:  16
DATALOADER_WORKERS: 16
EPOCH_TOTAL: 1000

LR: 3e-4
OPTI_DECAY_RATE: 0.8
OPTI_DECAY_INTERVAL: 80
OPTI_DECAY_MIN: 1e-6

LOG_DIR: 'nsc-v3.16-overfit4'
LOGGER: 'logger_s1'
LOGGER_SELECT: ['metric','image','model']
MODEL_SAVE_PER_N_EPOCH: 10
VIS_PER_N_BATCH: 5
VIS_ONE_PER_BATCH: True
VIS_TRAIN_PER_BATCH: 3

#RESUME: False
#MODEL_INIT_PATH: ['log/nsc-v3.16-pure-init/model/epoch_59.model']


RESUME: True
RESUME_EPOCH_ID: 55

BACKUP_FILES: ['core/net_bank/nsc_fusion.py',
               'core/net_bank/nsc_net_new.py',
               'core/net_bank/loss.py',
               'resource/data/index/car_2048_train.json',
               'resource/data/index/car_2048_vali.json',
               'resource/data/index/car_2048_test.json']