##################################################################################################
# dataset root
DATASET_ROOT: 'nocs_nips_all_dgx'
DATASET_CATES: ['02958343'] #'02691156',,'02958343']
# choose dataset
DATASET: 'sdf_nox_dataset'
DATASET_INDEX: ['resource/data/index/car_sdf_train.json',
                'resource/data/index/car_sdf_vali.json',
                'resource/data/index/car_sdf_test.json']
##################################################################################################
MODES: ['train','vali']
MODEL: 'sdfbaseline_v7_0'

GPU: [0,1,2,3]
BATCHSIZE:  64
DATALOADER_WORKERS: 20
EPOCH_TOTAL: 2000

LR: 3e-4
OPTI_DECAY_RATE: 0.8
OPTI_DECAY_INTERVAL: 100
OPTI_DECAY_MIN: 1e-8

LOG_DIR: 'sdf-v7.0-baseline-new'
LOGGER: 'logger_s1'
LOGGER_SELECT: ['metric','image','model']
MODEL_SAVE_PER_N_EPOCH: 1
VIS_PER_N_BATCH: 50
VIS_ONE_PER_BATCH: True
VIS_TRAIN_PER_BATCH: 50

#RESUME: False
#MODEL_INIT_PATH: ['log/nsc-v3.16-pure-init/model/epoch_59.model']


#RESUME: True
#RESUME_EPOCH_ID: 55

BACKUP_FILES: ['core/net_bank/deepsdf_net.py',
               'core/net_bank/loss.py',
               'resource/data/index/car_sdf_train.json',
               'resource/data/index/car_sdf_vali.json',
               'resource/data/index/car_sdf_test.json']