##################################################################################################
# dataset root
DATASET_ROOT: 'nocs_nips_all_dgx'
DATASET_CATES: ['02958343'] #'02691156',,'02958343']
# choose dataset
DATASET: 'nox_pc_dataset'
DATASET_INDEX: ['resource/data/index/car_2048_train.json',
                'resource/data/index/car_2048_vali.json',
                'resource/data/index/car_2048_test.json']
##################################################################################################
MODES: ['vali']
MODEL: 'super_nocs_v5_0_eval1'

GPU: [0,1,2,3]
BATCHSIZE: 8
DATALOADER_WORKERS: 16
EPOCH_TOTAL: 1000

LR: 1e-4
OPTI_DECAY_RATE: 0.5
OPTI_DECAY_INTERVAL: 10
OPTI_DECAY_MIN: 1e-7

LOG_DIR: 'super-nocs-v5.0-eval1'
LOGGER: 'logger_s1'
LOGGER_SELECT: ['metric','image','model']
MODEL_SAVE_PER_N_EPOCH: 1
VIS_PER_N_BATCH: 5
VIS_ONE_PER_BATCH: False
VIS_TRAIN_PER_BATCH: 20

RESUME: False
MODEL_INIT_PATH: ['log/super-nocs-v5.0/model/epoch_42.model']

BACKUP_FILES: ['core/net_bank/pointnet.py',
               'core/net_bank/nox_mlp.py',
               'core/net_bank/loss.py',
               'resource/data/index/car_2048_train.json',
               'resource/data/index/car_2048_vali.json',
               'resource/data/index/car_2048_test.json']