##################################################################################################
# dataset root
DATASET_ROOT: 'nocs_nips_all_net'
DATASET_CATES: ['02958343'] #'02691156',,'02958343']
# choose dataset
DATASET: 'nox_pc_overfit_dataset'
DATASET_INDEX: ['resource/data/index/car_2048_train.json',
                'resource/data/index/car_2048_vali.json',
                'resource/data/index/car_2048_test.json']
##################################################################################################
MODES: ['train']
MODEL: 'super_nocs_v5_2'

GPU: [0,1,2,3]
BATCHSIZE: 32
DATALOADER_WORKERS: 16
EPOCH_TOTAL: 1000

LR: 3e-4
OPTI_DECAY_RATE: 0.5
OPTI_DECAY_INTERVAL: 30
OPTI_DECAY_MIN: 1e-7

LOG_DIR: 'super-nocs-v5.2-overfit-onlyG'
LOGGER: 'logger_s1'
LOGGER_SELECT: ['metric','image','model']
MODEL_SAVE_PER_N_EPOCH: 5
VIS_PER_N_BATCH: 5
VIS_ONE_PER_BATCH: True
VIS_TRAIN_PER_BATCH: 5

RESUME: True
RESUME_EPOCH_ID: 20

BACKUP_FILES: ['core/net_bank/pointnet.py',
               'core/net_bank/nox_mlp.py',
               'core/net_bank/loss.py',
               'resource/data/index/car_2048_train.json',
               'resource/data/index/car_2048_vali.json',
               'resource/data/index/car_2048_test.json']