##################################################################################################
# dataset root
DATASET_ROOT: 'nocs_nips_all_net'
DATASET_CATES: ['03001627'] #'02691156',,'02958343']
# choose dataset
DATASET: 'nips_dataset'
DATASET_INDEX: ['resource/data/index/chair_2048_train.json',
                'resource/data/index/chair_2048_vali.json',
                'resource/data/index/chair_2048_test.json']
##################################################################################################
PROPORTION: 0.005
MODES: ['train'] #['vali','test']
MODEL: 'vgg_mlp_v8_0_super'

GPU: [0]
BATCHSIZE: 4
DATALOADER_WORKERS: 8
EPOCH_TOTAL: 2

LR: 3e-4
OPTI_DECAY_RATE: 0.5
OPTI_DECAY_INTERVAL: 50
OPTI_DECAY_MIN: 1e-8

LOG_DIR: 'vgg-mlp-v8.0-debugvis'
LOGGER: 'logger_s1'
LOGGER_SELECT: ['metric','image','model','xls']
MODEL_SAVE_PER_N_EPOCH: 1
VIS_PER_N_BATCH: 1
VIS_ONE_PER_BATCH: False
VIS_TRAIN_PER_BATCH: 1

#RESUME: True
#RESUME_EPOCH_ID: 22

RESUME: False
MODEL_INIT_PATH: ['log/vgg-mlp-v8.0-debugof/model/epoch_325.model']

BACKUP_FILES: ['core/net_bank/vgg.py',
               'core/net_bank/nox_mlp.py',
               'core/net_bank/loss.py',
               'resource/data/index/chair_2048_train.json',
               'resource/data/index/chair_2048_vali.json',
               'resource/data/index/chair_2048_test.json']