##################################################################################################
# dataset root
DATASET_ROOT: 'nocs_nips_all'
DATASET_CATES: ['02958343'] #'02691156',,'02958343']
# choose dataset
DATASET: 'nips_dataset'
DATASET_INDEX: ['resource/data/index/car_2048_train.json',
                'resource/data/index/car_2048_vali.json',
                'resource/data/index/car_2048_test.json']
##################################################################################################
MODES: ['train','vali']
MODEL: 'vgg_mlp_v8_2_2branch'

GPU: [0,1,2,3]
BATCHSIZE: 32
DATALOADER_WORKERS: 20
EPOCH_TOTAL: 2000

LR: 3e-4
OPTI_DECAY_RATE: 0.5
OPTI_DECAY_INTERVAL: 50
OPTI_DECAY_MIN: 1e-8

LOG_DIR: 'vgg-mlp-v8.2-syn'
LOGGER: 'logger_s1'
LOGGER_SELECT: ['metric','image','model','xls']
MODEL_SAVE_PER_N_EPOCH: 1
VIS_PER_N_BATCH: 10
VIS_ONE_PER_BATCH: True
VIS_TRAIN_PER_BATCH: 20

#RESUME: True
#RESUME_EPOCH_ID: 22

RESUME: False
MODEL_INIT_PATH: ['log/vgg-mlp-v8.2/model/epoch_39.model']

BACKUP_FILES: ['core/net_bank/vgg.py',
               'core/net_bank/nsc_net_new.py',
               'core/net_bank/loss.py',
               'resource/data/index/car_2048_train.json',
               'resource/data/index/car_2048_vali.json',
               'resource/data/index/car_2048_test.json']