##################################################################################################
# dataset root
DATASET_ROOT: 'nocs_nips_all_net'
DATASET_CATES: ['02958343'] #'02691156',,'02958343']
# choose dataset
DATASET: 'mv_correspondence_dataset'
PROPORTION: 1.0
DATASET_INDEX: ['resource/data/index/car_2048_train.json',
                'resource/data/index/car_2048_vali.json',
                'resource/data/index/car_2048_test.json']
##################################################################################################
MODES: ['vali']
MODEL: 'vi_mv_v8_62_eval'

GPU: [0]
BATCHSIZE: 2
DATALOADER_WORKERS: 8
EPOCH_TOTAL: 2

LR: 3e-4
OPTI_DECAY_RATE: 0.5
OPTI_DECAY_INTERVAL: 50
OPTI_DECAY_MIN: 1e-8

LOG_DIR: 'vi-mv-v8.6.2-p1-eval'
LOGGER: 'logger_s1'
LOGGER_SELECT: ['metric','image','model','xls']
MODEL_SAVE_PER_N_EPOCH: 1
VIS_PER_N_BATCH: 1
VIS_ONE_PER_BATCH: False
VIS_TRAIN_PER_BATCH: 1

#RESUME: True
#RESUME_EPOCH_ID: 22

RESUME: False
#MODEL_INIT_PATH: ['log/vi_mv_v8.6.2-p2/model/epoch_63.model']
MODEL_INIT_PATH: ['log/vi_mv_v8.6.2-p1/model/epoch_51.model']
#MODEL_INIT_PATH: ['log/SERVER-DOWNLOAD/vi_mv_v8.6_epoch_45.model']

BACKUP_FILES: ['core/net_bank/vgg.py',
               'core/net_bank/nox_mlp.py',
               'core/net_bank/loss.py',
               'resource/data/index/chair_2048_train.json',
               'resource/data/index/chair_2048_vali.json',
               'resource/data/index/chair_2048_test.json']