##################################################################################################
# dataset root
DATASET_ROOT: 'shapenet_plain'
DATASET_CATES: ['03001627'] # '02691156',,'02958343']
# choose dataset
DATASET: 'atlas_eval_2way_dataset'
PROPORTION: 1.0
#DATASET: 'nips_dataset'
#PROPORTION: 0.00025
DATASET_INDEX: ['resource/data/index/atlas_plane_test.json']
##################################################################################################
MODES: ['test']
MODEL: 'atlas_2way_eval'

GPU: [0]
BATCHSIZE: 2
DATALOADER_WORKERS: 10
EPOCH_TOTAL: 2

LR: 3e-5
OPTI_DECAY_RATE: 0.5
OPTI_DECAY_INTERVAL: 100
OPTI_DECAY_MIN: 1e-8

LOG_DIR: 'atlas-plane-2way'
LOGGER: 'logger_s1'
LOGGER_SELECT: ['metric','image','model','xls']
MODEL_SAVE_PER_N_EPOCH: 10
VIS_PER_N_EPOCH: 1
VIS_PER_N_BATCH: 3
VIS_ONE_PER_BATCH: True
VIS_TRAIN_PER_BATCH: 3

RESUME: False
MODEL_INIT_PATH: ['log/sv-plane-e70.model']

BACKUP_FILES: []