##################################################################################################
# new method, SegNet outputs unsupervised features
# trained on 8000 dataset

DATASET_ROOT: '/workspace/Data/full_hand_dataset/hand_rig_dataset_v3'
OUTPUT_DIR: '/workspace/nrnocs_dev/output/'

MODES: ['train','val']

BATCHSIZE: 2
DATALOADER_WORKERS: 2
EPOCH_TOTAL: 100

LR: 1e-3

SAVE_FREQ: 5
DATA_LIMIT: 100
IMAGE_SIZE: (320,240)
MODEL_INIT_PATH: ['log/hand_nocsreg_epoch_31.model']
TARGETS: "pnnocs00"
TASK: "pretrain"

NRNET_TYPE: "out_feature"
# NRNET_PRETRAIN: True
# NRNET_PRETRAIN_PATH: "/workspace/pretrained_weights/pnnocs/old_seg_100k"
OUT_CHANNELS: 4
FEATURE_CHANNELS: 64

EXPT_NAME: NRNet_out_pretrain_10k

GPU: 1