##################################################################################################
# Use the previous method, grab features from previous layer
# feed dirctly feed into the next network
# 

DATASET_ROOT: '/workspace/Data/8_7_cut_BW_IF'
OUTPUT_DIR: '/workspace/nrnocs_dev/output/'

MODES: ['train','val']

GPU: [1]
BATCHSIZE: 2
DATALOADER_WORKERS: 2
EPOCH_TOTAL: 100

LR: 1e-3

SAVE_FREQ: 5
DATA_LIMIT: 100
IMAGE_SIZE: (320,240)
MODEL_INIT_PATH: ['log/hand_nocsreg_epoch_31.model']
TARGETS: "pnnocs00"
TASK: "occupancy"

NRNET_TYPE: "inter_feature"
NRNET_PRETRAIN: True
NRNET_PRETRAIN_PATH: "/workspace/pretrained_weights/pnnocs/old_seg_100k"
OUT_CHANNELS: 4
FEATURE_CHANNELS: 128

EXPT_NAME: NRNet_inter_pretrain_10k


GPU: 3