##################################################################################################
# dataset root
DATASET_ROOT: '/workspace/Data/8_7_cut_BW_IF'
OUTPUT_DIR: '/workspace/nrnocs_dev/output/'

MODES: ['train','val']

GPU: [1]
BATCHSIZE: 2
DATALOADER_WORKERS: 4
EPOCH_TOTAL: 2

LR: 1e-3

SAVE_FREQ: 5
DATA_LIMIT: 100
IMAGE_SIZE: (320,240)
MODEL_INIT_PATH: ['log/hand_nocsreg_epoch_31.model']
TARGETS: "pnnocs00"
TASK: "occupancy"
OUT_CHANNELS: 68
EXPT_NAME: NRNet_10k


GPU: 2