##################################################################################################
# dataset root
DATASET_ROOT: 'shapenet_plain'
DATASET_CATES: ['03001627'] # '02691156',,'02958343']
# choose dataset
DATASET: 'p2m_eval_dataset'
PROPORTION: 1.0
#DATASET: 'nips_dataset'
#PROPORTION: 0.00025
DATASET_INDEX: ['resource/data/index/p2m_chair_test.json']
##################################################################################################
MODES: ['test']
MODEL: 'p2m_eval'

GPU: [2]
BATCHSIZE: 4
DATALOADER_WORKERS: 6
EPOCH_TOTAL: 2

LR: 3e-5
OPTI_DECAY_RATE: 0.5
OPTI_DECAY_INTERVAL: 100
OPTI_DECAY_MIN: 1e-8

LOG_DIR: 'p2m-chair-5v'
LOGGER: 'logger_s1'
LOGGER_SELECT: ['metric','image','model','xls']
MODEL_SAVE_PER_N_EPOCH: 10
VIS_PER_N_EPOCH: 1
VIS_PER_N_BATCH: 3
VIS_ONE_PER_BATCH: True
VIS_TRAIN_PER_BATCH: 3

BACKUP_FILES: []