##################################################################################################
# dataset root
DATASET_ROOT: 'shapenet_plain'
DATASET_CATES: ['02958343']
# choose dataset
DATASET: 'mv5_correspondence_dataset'
PROPORTION: 1.0
#DATASET: 'nips_dataset'
#PROPORTION: 0.00025
DATASET_INDEX: ['resource/data/index/shapenet_plain_car_train.json',
                'resource/data/index/shapenet_plain_car_test.json']
##################################################################################################
MODES: ['test']
MODEL: 'pix2surf_sv_mveval'

GPU: [0]
BATCHSIZE: 2
DATALOADER_WORKERS: 4
EPOCH_TOTAL: 2

LR: 0.0

LOG_DIR: 'verify-pix2surf-sv-mveval-car'
LOGGER: 'logger_s1'
LOGGER_SELECT: ['metric','image','model','xls']
MODEL_SAVE_PER_N_EPOCH: 1
VIS_PER_N_EPOCH: 1
VIS_PER_N_BATCH: 5
VIS_ONE_PER_BATCH: True
VIS_TRAIN_PER_BATCH: 3

#RESUME: True
#RESUME_EPOCH_ID: 400

RESUME: False
MODEL_INIT_PATH: ['log/pix2surf_sv_car_plain_epoch_51.model']

BACKUP_FILES: ['core/net_bank/vgg.py',
               'core/net_bank/uv_amp_mlp.py',
               'core/net_bank/loss.py']