##################################################################################################
# dataset root
DATASET_ROOT: 'shapenet_plain'
#DATASET_ROOT: 'nocs_nips_all'
DATASET_CATES: ['03001627'] #'02691156',,'02958343']
# choose dataset
DATASET: 'nips_dataset'
PROPORTION: 1.0
DATASET_INDEX: ['resource/data/index/shapenet_plain_chair_train.json',
                'resource/data/index/shapenet_plain_chair_test.json']
##################################################################################################
MODES: ['test']
MODEL: 'pix2surf_sv_eval'

GPU: [0]
BATCHSIZE: 8
DATALOADER_WORKERS: 6
EPOCH_TOTAL: 2

#LR: 0.0
#OPTI_DECAY_RATE: 0.5
#OPTI_DECAY_INTERVAL: 100
#OPTI_DECAY_MIN: 1e-8

LOG_DIR: 'pix2surf-sv-eval-chair'
LOGGER: 'logger_s1'
LOGGER_SELECT: ['metric','image','model','xls']
MODEL_SAVE_PER_N_EPOCH: 1
VIS_PER_N_EPOCH: 200
VIS_PER_N_BATCH: 1
VIS_ONE_PER_BATCH: False
VIS_TRAIN_PER_BATCH: 200


RESUME: False
MODEL_INIT_PATH: ['log/pix2surf_sv_chair_plain_epoch_120.model']



BACKUP_FILES: ['core/net_bank/vgg.py',
               'core/net_bank/uv_amp_mlp.py',
               'core/net_bank/loss.py']