##################################################################################################
# dataset root
DATASET_ROOT: 'shapenet_plain'
DATASET_CATES: ['03001627'] # '02691156',,'02958343']
# choose dataset
DATASET: 'mv5_correspondence_dataset'
PROPORTION: 1.0
DATASET_INDEX: ['resource/data/index/shapenet_plain_chair_train.json',
                'resource/data/index/shapenet_plain_chair_test.json']
##################################################################################################
MODES: ['train','test']
MODEL: 'pix2surf_mv'

GPU: [0,1]
BATCHSIZE: 4
DATALOADER_WORKERS: 6
EPOCH_TOTAL: 20000

LR: 1e-5
OPTI_DECAY_RATE: 0.5
OPTI_DECAY_INTERVAL: 100
OPTI_DECAY_MIN: 1e-8

LOG_DIR: 'pix2surf-mv-chair-plain'
LOGGER: 'logger_s1'
LOGGER_SELECT: ['metric','image','model','xls']
MODEL_SAVE_PER_N_EPOCH: 5
VIS_PER_N_EPOCH: 1
VIS_PER_N_BATCH: 100
VIS_ONE_PER_BATCH: True
VIS_TRAIN_PER_BATCH: 200

#RESUME: True
#RESUME_EPOCH_ID: 400

RESUME: False
MODEL_INIT_PATH: ['log/pix2surf-sv-chair-plain/model/epoch_120.model']


BACKUP_FILES: ['core/net_bank/vgg.py',
               'core/net_bank/uv_amp_mlp.py',
               'core/net_bank/loss.py']