##################################################################################################
# IF+NOCS
# Using the intermediate feature of SegNet
# pretrained weights from full dataset

# DATASET_ROOT: '/workspace/Data/8_7_cut_BW_IF'
DATASET_ROOT: '/workspace/Data/IF_PN_Aug13'
OUTPUT_DIR: '/workspace/nrnocs_dev/output/'

MODES: ['train','val']

BATCHSIZE: 1
DATALOADER_WORKERS: 2
EPOCH_TOTAL: 5

LR: 1e-4

SAVE_FREQ: 1
DATA_LIMIT: 100
IMAGE_SIZE: (320,240)
MODEL_INIT_PATH: ['log/hand_nocsreg_epoch_31.model']
TARGETS: "pnnocs00"
TASK: "occupancy"

NRNET_TYPE: "out_feature"
NRNET_PRETRAIN: True
NRNET_PRETRAIN_PATH: "/workspace/pretrained_weights/pnnocs/out_feat_100k"
OUT_CHANNELS: 4
FEATURE_CHANNELS: 64

UPDATE_SEG: False
# TEST_ON_TRAIN: True
# NR22:
# loss = nocs_loss + 10 * nocs_loss
# no batchnorm for the if-net
# freeze the segnet for 5 epochs
EXPT_NAME: "NR22" 

GPU: 2