##################################################################################################
# November 4th
# this is the multi-view baseline version of OccNet.
# We take multiple images of a frame
# enode them, and feed the features to OccNet

DATASET_ROOT: '/workspace/Data/SAPIEN/benchmark/glasses/mv8_scale_mpf_uni/'
OUTPUT_DIR: '/workspace/dev_nrnocs/output/expt/'
VIEW_NUM: 2

BATCHSIZE: 32
DATALOADER_WORKERS: 4
EPOCH_TOTAL: 500

LR: 1e-4
DATA_LIMIT: 100
# DATA_LIMIT: 1
VAL_DATA_LIMIT: 5
# VAL_DATA_LIMIT: 1

# EXPT_NAME: "occ_baseline_b1"
EXPT_NAME: "occ_baseline_new"
ONET_CANO: True

GPU: 3
TEST_ON_TRAIN: False
# TEST_ON_TRAIN: True

###################################################
MODES: ['train','val']
# MODES: ['val']
LR: 1e-4

