##################################################################################################
# Oct 20
# DATASET_ROOT: '/workspace/Data/SAPIEN/laptop/laptop_nocs_500_30_full_IF'
# this mode runs good! let's just see how it perform

DATASET_ROOT: '/workspace/Data/SAPIEN/benchmark/glasses/mv8_fix_scale_mpf_nobg_uni'
OUTPUT_DIR: '/workspace/dev_nrnocs/output/expt/gls'

BATCHSIZE: 1
DATALOADER_WORKERS: 4
EPOCH_TOTAL: 20

LR: 1e-4
DATA_LIMIT: 100
VAL_DATA_LIMIT: 3
EXPT_NAME: "occ_posed"

# ONET_CANO: True

GPU: 7
TEST_ON_TRAIN: False
# TEST_ON_TRAIN: True

###################################################
MODES: ['train','val']
# MODES: ['val']
LR: 1e-4

