##################################################################################################
# Oct 20
# DATASET_ROOT: '/workspace/Data/SAPIEN/laptop/laptop_nocs_500_30_full_IF'
# this mode runs good! let's just see how it perform

DATASET_ROOT: '/workspace/Data/SAPIEN/benchmark/glasses/mv8_fix_scale_mpf_nobg_uni'
OUTPUT_DIR: '/workspace/dev_nrnocs/output/expt/gls'

VIEW_NUM: 1
RANDOM_VIEW: True
TOTAL_VIEW: 8

BATCHSIZE: 1
DATALOADER_WORKERS: 4
EPOCH_TOTAL: 35

LR: 1e-4
DATA_LIMIT: 100
VAL_DATA_LIMIT: 100
EXPT_NAME: "r8_v1_mp"

ONET_MV_CANO: False

GPU: 4
TEST_ON_TRAIN: False
# TEST_ON_TRAIN: True

###################################################
MODES: ['train','val']
# MODES: ['val']
LR: 1e-4

