# main table xnocs (sv) training
##################################################################################################
# dataset root
DATASET_ROOT: 'shapenet_plain'
DATASET_CATES: ['03001627'] #'02691156',,'02958343','02958343']
# choose dataset
DATASET: 'nips_dataset'
PROPORTION: 1.0
DATASET_INDEX: ['resource/data/index/shapenet_plain_chair_train.json',
                'resource/data/index/shapenet_plain_chair_test.json']

##################################################################################################
MODES: ['train','test']
MODEL: 'nips_baseline_bce'

GPU: [0]
BATCHSIZE:  2
DATALOADER_WORKERS: 6
EPOCH_TOTAL: 200

LR: 1e-4
OPTI_DECAY_RATE: 0.5
OPTI_DECAY_INTERVAL: 100
OPTI_DECAY_MIN: 1e-8

LOG_DIR: 'dev-eccv-xnocs-bce-sv-chair-plain-b2'
LOGGER: 'logger_s1'
LOGGER_SELECT: ['metric','image','model']
MODEL_SAVE_PER_N_EPOCH: 3
VIS_PER_N_BATCH: 100
VIS_ONE_PER_BATCH: True
VIS_TRAIN_PER_BATCH: 200

BACKUP_FILES: ['core/net_bank/nips_nox_network.py',
               'core/net_bank/loss.py']