##################################################################################################
# dataset root
DATASET_ROOT: 'atlasnet_pc'
DATASET_CATES: ['03001627'] #'02691156',,'02958343']
# choose dataset
DATASET: 'point_cloud_dataset'
#DATASET: 'nocs_atlas_dataset'
PROPORTION: 1.0
DATASET_INDEX: ['resource/data/index/shapenet_coco_split.json']
##################################################################################################
MODES: ['vali']
MODEL: 'paramenet_v2'

GPU: [0]
BATCHSIZE: 2
DATALOADER_WORKERS: 4
EPOCH_TOTAL: 2

LR: 3e-5
OPTI_DECAY_RATE: 0.5
OPTI_DECAY_INTERVAL: 250
OPTI_DECAY_MIN: 1e-8

LOG_DIR: 'paramenet-v2-chair-eval'
LOGGER: 'logger_s1'
LOGGER_SELECT: ['metric','image','model','xls']
MODEL_SAVE_PER_N_EPOCH: 1
VIS_PER_N_EPOCH: 1
VIS_PER_N_BATCH: 1
VIS_ONE_PER_BATCH: False
VIS_TRAIN_PER_BATCH: 1

#RESUME: True
#RESUME_EPOCH_ID: 190

RESUME: False
MODEL_INIT_PATH: ['log/paramenet_v2_epoch_720.model']
#MODEL_INIT_PATH: ['log1/SERVER-DOWNLOAD/vgg_car_epoch_60.model']
#MODEL_INIT_PATH: ['log/sv-v1-cell-p1/model/epoch_30.model']

BACKUP_FILES: ['core/net_bank/pointnet.py',
               'core/net_bank/uv_amp_mlp.py',
               'core/net_bank/loss.py',
               'resource/data/index/shapenet_coco_split.json']