##################################################################################################
# Oct 20
# DATASET_ROOT: '/workspace/Data/SAPIEN/laptop/laptop_nocs_500_30_full_IF'
# this mode runs good! let's just see how it perform

DATASET_ROOT: '/workspace/Data/SAPIEN/eyeglasses/aug_scale_mpf_uni'
OUTPUT_DIR: '/workspace/dev_nrnocs/output/expt/'

BATCHSIZE: 32
DATALOADER_WORKERS: 4
EPOCH_TOTAL: 2000

LR: 1e-4
DATA_LIMIT: 100
# DATA_LIMIT: 1
VAL_DATA_LIMIT: 100
# VAL_DATA_LIMIT: 1
EXPT_NAME: "occ_b64"

GPU: 7
TEST_ON_TRAIN: False
# TEST_ON_TRAIN: True

###################################################
MODES: ['train','val']
# MODES: ['val']
LR: 1e-4

