##################################################################################################
# Oct 20
# DATASET_ROOT: '/workspace/Data/SAPIEN/laptop/laptop_nocs_500_30_full_IF'
# this mode runs good! let's just see how it perform


DATASET_ROOT: '/workspace/Data/SAPIEN/laptop/mv_laptop_500_4_IF'
OUTPUT_DIR: '/workspace/dev_nrnocs/output/mv'
VIEW_NUM: 2
MODES: ['train','val']
# MODES: ['val']

BATCHSIZE: 1
DATALOADER_WORKERS: 4
EPOCH_TOTAL: 20

LR: 1e-4

SAVE_FREQ: 1
DATA_LIMIT: 100
VAL_DATA_LIMIT: 2
IMAGE_SIZE: (320,240)
TARGETS: ["default"]

TASK: "mlnrnet"
EXPT_NAME: "if1"
IF_IN_DIM: 16 # just for comparison

OUT_CHANNELS: 12 #4 + 1*8

# TEST_ON_TRAIN: True
TEST_ON_TRAIN: False

MH: True
BN: False

# NOCS_LOSS: 10
NOCS_LOSS: 1
POSE_LOSS: 1
POSE_MAP_LOSS: 1
LOC_LOSS: 1
LOC_MAP_LOSS: 1
SKIN_LOSS: 1

BONE_NUM: 1

REPOSE: True
# STAGE_ONE: True
STAGE_ONE: False

AGGR_SCATTER: True

NRNET_PRETRAIN: True
NRNET_PRETRAIN_PATH: "/workspace/dev_nrnocs/output/mv/stg1/test1_9999-12-31T23-59-59.tar"

GPU: 2
