##################################################################################################
# dataset root
DATASET_ROOT: 'nocs_nips_all'
DATASET_CATES: ['03001627'] #'02691156',,'02958343']
# choose dataset
DATASET: 'mv_correspondence_dataset'
PROPORTION: 1.0
DATASET_INDEX: ['resource/data/index/car_2048_train.json',
                'resource/data/index/car_2048_vali.json',
                'resource/data/index/car_2048_test.json']
##################################################################################################
MODES: ['train','vali']
MODEL: 'final_v2'

GPU: [0,1,2,3]
BATCHSIZE: 8
DATALOADER_WORKERS: 6
EPOCH_TOTAL: 20000

LR: 3e-5
OPTI_DECAY_RATE: 0.5
OPTI_DECAY_INTERVAL: 100
OPTI_DECAY_MIN: 1e-8

LOG_DIR: 'final-v2-mv-mc-car'
LOGGER: 'logger_s1'
LOGGER_SELECT: ['metric','image','model','xls']
MODEL_SAVE_PER_N_EPOCH: 10
VIS_PER_N_EPOCH: 1
VIS_PER_N_BATCH: 15
VIS_ONE_PER_BATCH: True
VIS_TRAIN_PER_BATCH: 30

#RESUME: True
#RESUME_EPOCH_ID: 400

RESUME: False
MODEL_INIT_PATH: ['log/final-car-sv-sc-v0/model/epoch_25.model']
#MODEL_INIT_PATH: ['log1/SERVER-DOWNLOAD/nsc_v9.8_chair_epoch_13.model']
#MODEL_INIT_PATH: ['log1/SERVER-DOWNLOAD/v8.7.7.4_epoch_53.model']
#MODEL_INIT_PATH: ['log/force-v9.9-nsc-multi-chart/model/epoch_12000.model']

BACKUP_FILES: ['core/net_bank/vgg.py',
               'core/net_bank/uv_amp_mlp.py',
               'core/net_bank/loss.py',
               'resource/data/index/car_2048_train.json',
               'resource/data/index/car_2048_vali.json',
               'resource/data/index/car_2048_test.json']