##################################################################################################
# dataset root
DATASET_ROOT: 'nocs_nips_all'
DATASET_CATES: ['03001627'] #'02691156',,'02958343','02958343']
# choose dataset
DATASET: 'nips_dataset'
DATASET_INDEX: ['resource/data/index/chair_2048_train.json',
                'resource/data/index/chair_2048_vali.json',
                'resource/data/index/chair_2048_test.json']
##################################################################################################
MODES: ['train','vali']
MODEL: 'nips_baseline'

GPU: [0,1,2,3]
BATCHSIZE:  32
DATALOADER_WORKERS: 20
EPOCH_TOTAL: 2000

LR: 1e-4
OPTI_DECAY_RATE: 0.5
OPTI_DECAY_INTERVAL: 100
OPTI_DECAY_MIN: 1e-8

LOG_DIR: 'nips-baseline-chair'
LOGGER: 'logger_s1'
LOGGER_SELECT: ['metric','image','model']
MODEL_SAVE_PER_N_EPOCH: 1
VIS_PER_N_BATCH: 10
VIS_ONE_PER_BATCH: True
VIS_TRAIN_PER_BATCH: 20

#RESUME: False
#MODEL_INIT_PATH: ['log/nocsdf-v7.1-p1/model/epoch_27.model']

RESUME: True
RESUME_EPOCH_ID: 10

BACKUP_FILES: ['core/net_bank/nips_nox_network.py',
               'core/net_bank/loss.py',
               'resource/data/index/chair_2048_train.json',
               'resource/data/index/chair_2048_vali.json',
               'resource/data/index/chair_2048_test.json']