##################################################################################################
# dataset root
DATASET_ROOT: 'shapenet_plain'
DATASET_CATES: ['03001627'] # '02691156',,'02958343']
# choose dataset
DATASET: 'mv5_correspondence_dataset'
PROPORTION: 1.0
#DATASET: 'nips_dataset'
#PROPORTION: 0.00025
DATASET_INDEX: ['resource/data/index/shapenet_plain_chair_train.json',
                'resource/data/index/shapenet_plain_chair_test.json']
##################################################################################################
MODES: ['test']
MODEL: 'pixel2surf_mv_eval_compare'

GPU: [2]
BATCHSIZE: 3
DATALOADER_WORKERS: 20
EPOCH_TOTAL: 20000

LR: 3e-5
OPTI_DECAY_RATE: 0.5
OPTI_DECAY_INTERVAL: 100
OPTI_DECAY_MIN: 1e-8

LOG_DIR: 'pixel2surf-chair-eval-mv5-compare-e70'
LOGGER: 'logger_s1'
LOGGER_SELECT: ['metric','image','model','xls']
MODEL_SAVE_PER_N_EPOCH: 1
VIS_PER_N_EPOCH: 1
VIS_PER_N_BATCH: 3
VIS_ONE_PER_BATCH: True
VIS_TRAIN_PER_BATCH: 3

#RESUME: True
#RESUME_EPOCH_ID: 400

RESUME: False
#MODEL_INIT_PATH: ['log/pixel2surf-mv-chair-raw/model/epoch_latest.model']
#MODEL_INIT_PATH: ['log1/SERVER-DOWNLOAD/nsc_v9.8_chair_epoch_13.model']
#MODEL_INIT_PATH: ['log1/SERVER-DOWNLOAD/vgg_chair_epoch_30.model']
MODEL_INIT_PATH: ['log/sv-chair-e70.model']

BACKUP_FILES: ['core/net_bank/vgg.py',
               'core/net_bank/uv_amp_mlp.py',
               'core/net_bank/loss.py',
               'resource/data/index/shapenet_plain_chair_train.json',
               'resource/data/index/shapenet_plain_chair_test.json']