##################################################################################################
# dataset root
DATASET_ROOT: 'nocs_nips_all'
DATASET_CATES: ['02958343'] # '02691156',,'02958343']
# choose dataset
DATASET: 'mv5_correspondence_dataset'
PROPORTION: 1.0
#DATASET: 'nips_dataset'
#PROPORTION: 0.00025
DATASET_INDEX: ['resource/data/index/car_2048_train.json',
                'resource/data/index/car_2048_vali.json',
                'resource/data/index/car_2048_test.json']
##################################################################################################
MODES: ['train','vali']
MODEL: 'sup_mv_nocsmlp'

GPU: [0,1,2,3]
BATCHSIZE: 8
DATALOADER_WORKERS: 16
EPOCH_TOTAL: 20000

LR: 1e-4
OPTI_DECAY_RATE: 0.5
OPTI_DECAY_INTERVAL: 100
OPTI_DECAY_MIN: 1e-8

LOG_DIR: 'sup-mv5-car-nocsmlp'
LOGGER: 'logger_s1'
LOGGER_SELECT: ['metric','image','model','xls']
MODEL_SAVE_PER_N_EPOCH: 1
VIS_PER_N_EPOCH: 1
VIS_PER_N_BATCH: 10
VIS_ONE_PER_BATCH: True
VIS_TRAIN_PER_BATCH: 30

#RESUME: True
#RESUME_EPOCH_ID: 400

RESUME: False
#MODEL_INIT_PATH: ['log/pixel2surf-mv-car-raw/model/epoch_latest.model']
#MODEL_INIT_PATH: ['log1/SERVER-DOWNLOAD/nsc_v9.8_car_epoch_13.model']
#MODEL_INIT_PATH: ['log1/SERVER-DOWNLOAD/vgg_car_epoch_30.model']
MODEL_INIT_PATH: ['log/nocsmlp_car_e33.model']


BACKUP_FILES: ['core/net_bank/vgg.py',
               'core/net_bank/uv_amp_mlp.py',
               'core/net_bank/loss.py',
               'resource/data/index/car_2048_train.json',
               'resource/data/index/car_2048_vali.json',
               'resource/data/index/car_2048_test.json']