##################################################################################################
# Oct 15


DATASET_ROOT: '/workspace/Data/SAPIEN/dishwasher/dishwasher_500_14_IF'
OUTPUT_DIR: '/workspace/dev_nrnocs/output/dishwasher'

MODES: ['train','val']

BATCHSIZE: 2
DATALOADER_WORKERS: 4
EPOCH_TOTAL: 20

LR: 1e-4

SAVE_FREQ: 1
DATA_LIMIT: 100 
VAL_DATA_LIMIT: 5
IMAGE_SIZE: (320,240)
TARGETS: ["default"]
TASK: "lnrnet"
OUT_CHANNELS: 12 #4 + 1*8

TEST_ON_TRAIN: True

MH: True
BN: False

# NOCS_LOSS: 10
NOCS_LOSS: 1
POSE_LOSS: 10
POSE_MAP_LOSS: 1
LOC_LOSS: 10
LOC_MAP_LOSS: 1
SKIN_LOSS: 1

BONE_NUM: 1

REPOSE: True
# STAGE_ONE: True
STAGE_ONE: False

EXPT_NAME: "nocs_14_hp"

# NRNET_PRETRAIN: True
# NRNET_PRETRAIN_PATH: "/workspace/pretrained_weights/nocs_30_b2_bkup"

GPU: 2


