##################################################################################################
# Here we train the first stage with all the tricks:
# 1. with enriching feature
# 2. with consistency loss
# 3. multi view
# 4. random views


DATASET_ROOT: '/workspace/Data/SAPIEN/benchmark/oven/benchmark_v1_uni/'
OUTPUT_DIR: '/workspace/dev_nrnocs/output/benchmark/oven/'

BATCHSIZE: 1
DATALOADER_WORKERS: 5
EPOCH_TOTAL: 4 # 4 + 1

DATA_LIMIT: 20 # make the shuffle thing to make sure we have seen every view
VAL_DATA_LIMIT: 5
IMAGE_SIZE: (320,240)
TARGETS: ["default"]

TASK: "lnrnet"
EXPT_NAME: "recon_bm1_nobg_sv" ## This is the result with back ground! I wrote it wrong! V2 actually
BONE_NUM: 1
GPU: 3

OUT_CHANNELS: 12 #4 + 1*8
# TEST_ON_TRAIN: True
TEST_ON_TRAIN: False

# IF_IN_DIM: 32

REPOSE: True
STAGE_ONE: False

###################################################
MODES: ['train','val']
# MODES: ['val']
LR: 1e-4
SAVE_FREQ: 5
MH: True
MH: True
BN: False

# Try training with CRR loss *10 from the  middle of training
# NOCS_LOSS: 10
NOCS_LOSS: 1
POSE_LOSS: 1
POSE_MAP_LOSS: 1
LOC_LOSS: 1
LOC_MAP_LOSS: 1
SKIN_LOSS: 1
RECON_LOSS: 0.1


AGGR_SCATTER: True
NRNET_PRETRAIN: True
NRNET_PRETRAIN_PATH: "/workspace/dev_nrnocs/output/benchmark/oven/stg1_bm1_nobg/stg1_bm1_nobg_9999-12-31T23-59-59.tar"