##################################################################################################
# Here we train the first stage with all the tricks:
# 1. with enriching feature
# 2. with consistency loss
# 3. multi view
# 4. random views


DATASET_ROOT: '/workspace/Data/SAPIEN/benchmark/oven/benchmark_v1_uni/'
OUTPUT_DIR: '/workspace/dev_nrnocs/output/benchmark/oven/'

BATCHSIZE: 1
DATALOADER_WORKERS: 5
EPOCH_TOTAL: 30

DATA_LIMIT: 100
VAL_DATA_LIMIT: 5
IMAGE_SIZE: (320,240)
TARGETS: ["default"]

TASK: "mlnrnet"
EXPT_NAME: "stg1_bm1_nobg_sv" ## This is the result with back ground! I wrote it wrong! V2 actually
BONE_NUM: 1
GPU: 0
OUT_CHANNELS: 12 #4 + 1*8
TEST_ON_TRAIN: False

REPOSE: True
STAGE_ONE: True

###################################################
MODES: ['train','val']
LR: 1e-4
SAVE_FREQ: 5
MH: True
BN: False

NOCS_LOSS: 1
POSE_LOSS: 1
POSE_MAP_LOSS: 1
LOC_LOSS: 1
LOC_MAP_LOSS: 1
SKIN_LOSS: 1
RECON_LOSS: 0.1


AGGR_SCATTER: True