##################################################################################################
# IF+NOCS
# Using the intermediate feature of SegNet
# pretrained weights from full dataset

# DATASET_ROOT: '/workspace/Data/8_7_cut_BW_IF'
DATASET_ROOT: '/workspace/Data/IF_CUT'
OUTPUT_DIR: '/workspace/nrnocs_dev/output/'

MODES: ['train','val']

BATCHSIZE: 2
DATALOADER_WORKERS: 2
EPOCH_TOTAL: 100

LR: 1e-3

TEST_ON_TRAIN: True
SAVE_FREQ: 5
DATA_LIMIT: 1
IMAGE_SIZE: (320,240)
MODEL_INIT_PATH: ['log/hand_nocsreg_epoch_31.model']
TARGETS: "pnnocs00"
TASK: "occupancy"

NRNET_TYPE: "inter_feature"
NRNET_PRETRAIN: True
NRNET_PRETRAIN_PATH: "/workspace/pretrained_weights/pnnocs/old_seg_100k/"
OUT_CHANNELS: 4
FEATURE_CHANNELS: 128

EXPT_NAME: "inter_overfit"

GPU: 3