##################################################################################################
# November 4th
# this is the multi-view baseline version of OccNet.
# We take multiple images of a frame
# enode them, and feed the features to OccNet

DATASET_ROOT: '/workspace/Data/SAPIEN/benchmark/laptop/benchmark_v1_uni/'
OUTPUT_DIR: '/workspace/dev_nrnocs/output/expt/laptop'
VIEW_NUM: 4
RANDOM_VIEW: True
TOTAL_VIEW: 8

# BATCHSIZE: 32
BATCHSIZE: 1
DATALOADER_WORKERS: 2
EPOCH_TOTAL: 35
SAVE_FREQ: 5

LR: 1e-4
DATA_LIMIT: 100
VAL_DATA_LIMIT: 20

EXPT_NAME: "occ_4v_b1"
ONET_CANO: True

GPU: 1
TEST_ON_TRAIN: False

###################################################
MODES: ['train','val']
# MODES: ['val']
LR: 1e-4