##################################################################################################
# IF+NOCS
# Using the intermediate feature of SegNet
# pretrained weights from full dataset

# DATASET_ROOT: '/workspace/Data/8_7_cut_BW_IF'
DATASET_ROOT: '/workspace/Data/SAPIEN/pose_aa_IF'
OUTPUT_DIR: '/workspace/nrnocs_dev/output/'

MODES: ['train','val']

BATCHSIZE: 2
DATALOADER_WORKERS: 2
EPOCH_TOTAL: 100

LR: 1e-5

SAVE_FREQ: 2
DATA_LIMIT: 100 # 10 percent
IMAGE_SIZE: (320,240)
TARGETS: "default"
TASK: "sapien_lbs"
OUT_CHANNELS: 20 #4 + 2*8

TEST_ON_TRAIN: True

# NOCS_LOSS: True
POSE_LOSS: True
POSE_MAP_LOSS: True

BONE_NUM: 2

EXPT_NAME: "sapien_pose_aa2"
GPU: 0