##################################################################################################
# dataset root
DATASET_ROOT: '/workspace/Data/Tmp_82/'
OUTPUT_DIR: '/workspace/NRNOCS/debug/'

# choose dataset
# new json index, only used for debug
##################################################################################################
MODES: ['train','val']

GPU: [1]
BATCHSIZE: 2
DATALOADER_WORKERS: 4
EPOCH_TOTAL: 2000

LR: 1e-3

SAVE_FREQ: 100
DATA_LIMIT: 2
IMAGE_SIZE: (320,240)
MODEL_INIT_PATH: ['log/hand_nocsreg_epoch_31.model']
# EXPT_NAME: debug_28
EXPT_NAME: lbs_skin
# EXPT_NAME: debug_29_woSkip