##################################################################################################
# dataset root
DATASET_ROOT: 'nocs_nips_all'
DATASET_CATES: ['02958343']#'02691156',,'02958343']
# choose dataset
DATASET: 'fishscale_dataset'
##################################################################################################
MODES: ['vali']
MODEL: 'fishscale_v0'

GPU: [0,1,3]
BATCHSIZE: 96
DATALOADER_WORKERS: 24
EPOCH_TOTAL: 1

LR: 3e-4
OPTI_DECAY_RATE: 0.5
OPTI_DECAY_INTERVAL: 20
OPTI_DECAY_MIN: 1e-6

LOG_DIR: 'fishscale-v0.1.0-vis'
LOGGER: 'logger_s1'
LOGGER_SELECT: ['metric','image','pc','model']
MODEL_SAVE_PER_N_EPOCH: 1
VIS_PER_N_BATCH: 5
VIS_ONE_PER_BATCH: False
VIS_TRAIN_PER_BATCH: 40
BACKUP_FILES: ['core/net_bank/fishscalenet.py']

RESUME: False
MODEL_INIT_PATH: ['log/milestone/fishscale_v0.1.0_epoch_28.model']