##################################################################################################
# dataset root
DATASET_ROOT: 'nocs_nips_all'
DATASET_CATES: ['02958343'] #'02691156',,'02958343']
# choose dataset
DATASET: 'fishscale_dataset_v2'
##################################################################################################
MODES: ['train','vali']
MODEL: 'fishscale_v1_1_1'

GPU: [0,1,2,3]
BATCHSIZE: 60
DATALOADER_WORKERS: 24
EPOCH_TOTAL: 1000

LR: 3e-4
OPTI_DECAY_RATE: 0.8
OPTI_DECAY_INTERVAL: 8
OPTI_DECAY_MIN: 1e-6

LOG_DIR: 'fishscale-v1.1.1'
LOGGER: 'logger_s1'
LOGGER_SELECT: ['metric','image','pc','model']
MODEL_SAVE_PER_N_EPOCH: 1
VIS_PER_N_BATCH: 5
VIS_ONE_PER_BATCH: True
VIS_TRAIN_PER_BATCH: 20
BACKUP_FILES: ['core/net_bank/fishscalenet.py']