##################################################################################################
# dataset root
DATASET_ROOT: 'nocs_nips_all'
DATASET_CATES: ['02958343']#'02691156',,'02958343']
# choose dataset
DATASET: 'fishscale_dataset'
##################################################################################################
MODES: ['train','vali']
MODEL: 'fishscale_v0'

GPU: [0]
BATCHSIZE: 16
DATALOADER_WORKERS: 16
EPOCH_TOTAL: 1000

LR: 1e-4
OPTI_DECAY_RATE: 0.7
OPTI_DECAY_INTERVAL: 40
OPTI_DECAY_MIN: 1e-8

LOG_DIR: 'fishscale-dbg'
LOGGER: 'logger_s1'
LOGGER_SELECT: ['metric','image','pc','model']
MODEL_SAVE_PER_N_EPOCH: 1
VIS_PER_N_BATCH: 10
VIS_ONE_PER_BATCH: True
VIS_TRAIN_PER_BATCH: 50
BACKUP_FILES: ['core/net_bank/fishscalenet.py']