##################################################################################################
# dataset root
DATASET_ROOT: 'nocs_nips_mini'
DATASET_CATES: ['02958343'] #'02691156',,'02958343']
# choose dataset
DATASET: 'vanilla_nocs_dataset_v2_mv'
##################################################################################################
MODES: ['vali']
MODEL: 'nocs_reg_mv'

GPU: [0]
BATCHSIZE: 2
DATALOADER_WORKERS: 1
EPOCH_TOTAL: 1

LR: 3e-4
OPTI_DECAY_RATE: 0.5
OPTI_DECAY_INTERVAL: 20
OPTI_DECAY_MIN: 1e-6

LOG_DIR: 'vanilla-nocs-v2-mv'
LOGGER: 'logger_s1'
LOGGER_SELECT: ['metric','image','model','poisson-surface']
MODEL_SAVE_PER_N_EPOCH: 3
VIS_PER_N_BATCH: 1
VIS_ONE_PER_BATCH: False
VIS_TRAIN_PER_BATCH: 40
BACKUP_FILES: ['core/net_bank/uresnet.py']

RESUME: False
MODEL_INIT_PATH: ['log/milestone/vanilla_nocs_v2_reg_epoch_21.model']