DATASET_ROOT: '/data/new_disk2/zhangge/Data/SAPIEN/benchmark/glasses/mv8_fix_scale_mpf_nobg_uni/'
OUTPUT_DIR: '/data/new_disk2/zhangge/StrobeNet/output/mv/gls/stg2/'
VIEW_NUM: 2 # we use random views this time
RANDOM_VIEW: True
TOTAL_VIEW: 8

BATCHSIZE: 1
DATALOADER_WORKERS: 5
EPOCH_TOTAL: 5

DATA_LIMIT: 100
VAL_DATA_LIMIT: 20
IMAGE_SIZE: (320,240)
TARGETS: ["default"]

# TASK: "mvmp"
TASK: "mlnrnet"
EXPT_NAME: "2v_1crr"
RESOLUTION: 128

BONE_NUM: 2
GPU: 7

TEST_ON_TRAIN: False

REPOSE: True

STAGE_ONE: False

###################################################
MODES: ['train','val']
# MODES: ['val']
LR: 1e-4
SAVE_FREQ: 1
MH: True
BN: False


CONSISTENCY: 1.0

NOCS_LOSS: 1
POSE_LOSS: 1
POSE_MAP_LOSS: 1
LOC_LOSS: 1
LOC_MAP_LOSS: 1
SKIN_LOSS: 1
RECON_LOSS: 0.1

AGGR_SCATTER: True
NRNET_PRETRAIN: True
NRNET_PRETRAIN_PATH: "/data/new_disk2/zhangge/StrobeNet/output/mv/gls/stg1_1crr_2v/stg1_1crr_2v_9999-12-31T23-59-59.tar"