##################################################################################################
# Here we train the first stage with all the tricks:
# 1. with enriching feature
# 2. with consistency loss
# 3. multi view
# 4. random views

DATASET_ROOT: '/workspace/Data/SAPIEN/benchmark/laptop/benchmark_v1_uni/'
OUTPUT_DIR: '/workspace/dev_nrnocs/output/benchmark/laptop/'
VIEW_NUM: 3 # we use random views this time
VAL_DIR: "i3"
GPU: 1

RANDOM_VIEW: True
TOTAL_VIEW: 8

BATCHSIZE: 1
DATALOADER_WORKERS: 2
EPOCH_TOTAL: 5

DATA_LIMIT: 100
VAL_DATA_LIMIT: 5
IMAGE_SIZE: (320,240)
TARGETS: ["default"]

TASK: "mlnrnet"
EXPT_NAME: "open_recon_bm1_early"
BONE_NUM: 1

OUT_CHANNELS: 12 #4 + 1*8
TEST_ON_TRAIN: False

REPOSE: True
STAGE_ONE: False

###################################################
MODES: ['train','val']
# MODES: ['val']
LR: 1e-4
SAVE_FREQ: 1
MH: True
BN: False

CONSISTENCY: 1
NOCS_LOSS: 1
POSE_LOSS: 1
POSE_MAP_LOSS: 1
LOC_LOSS: 1
LOC_MAP_LOSS: 1
SKIN_LOSS: 1
RECON_LOSS: 0.1


AGGR_SCATTER: True
NRNET_PRETRAIN: True
NRNET_PRETRAIN_PATH: "/workspace/dev_nrnocs/output/benchmark/laptop/stg1_bm/stg1_bm_2020-11-07T20-46-36_1604781996752043.tar"