##################################################################################################
# IF+NOCS
# Using the intermediate feature of SegNet
# pretrained weights from full dataset

# DATASET_ROOT: '/workspace/Data/8_7_cut_BW_IF'
DATASET_ROOT: '/workspace/Data/SAPIEN/5obj_IF'
OUTPUT_DIR: '/workspace/nrnocs_dev/output/'

MODES: ['train','val']

BATCHSIZE: 2
DATALOADER_WORKERS: 2
EPOCH_TOTAL: 10000

LR: 1e-4

SAVE_FREQ: 100
DATA_LIMIT: 2 # 10 percent
IMAGE_SIZE: (320,240)
TARGETS: "default"
TASK: "sapien_lbs"
OUT_CHANNELS: 28 #4 + 3*8

TEST_ON_TRAIN: True

# NOCS_LOSS: True
POSE_LOSS: True
POSE_MAP_LOSS: True

BONE_NUM: 3

EXPT_NAME: "sapien_pose_1"
GPU: 2