##################################################################################################
# Here we train the first stage with all the tricks:
# 1. with enriching feature
# 2. with consistency loss
# 3. multi view
# 4. random views

DATASET_ROOT: '/workspace/Data/SAPIEN/benchmark/glasses/mv8_fix_scale_mpf_nobg_uni/'
OUTPUT_DIR: '/workspace/dev_nrnocs/output/benchmark/glasses/'
VIEW_NUM: 4 # we use random views this time
# VIEW_NUM: 4 # we use random views this time
RANDOM_VIEW: True
TOTAL_VIEW: 8

BATCHSIZE: 1
DATALOADER_WORKERS: 5
EPOCH_TOTAL: 5 # 30 + 5 to get converge

DATA_LIMIT: 100
VAL_DATA_LIMIT: 5
IMAGE_SIZE: (320,240)
TARGETS: ["default"]

# TASK: "mvmp"
TASK: "mlnrnet"
EXPT_NAME: "big_stg1_fix_nobg_4v"
RESOLUTION: 128

BONE_NUM: 2
GPU: 6
OUT_CHANNELS: 12 #4 + 1*8
# TEST_ON_TRAIN: True
TEST_ON_TRAIN: False

REPOSE: True
STAGE_ONE: True

###################################################
MODES: ['train','val']
# MODES: ['val']
LR: 1e-4
SAVE_FREQ: 5
MH: True
BN: False

# CONSISTENCY: 1
CONSISTENCY: 1
# Try training with CRR loss *10 from the  middle of training
# NOCS_LOSS: 10
NOCS_LOSS: 1
POSE_LOSS: 1
POSE_MAP_LOSS: 1
LOC_LOSS: 1
LOC_MAP_LOSS: 1
SKIN_LOSS: 1
RECON_LOSS: 0.1

AGGR_SCATTER: True

