##################################################################################################
# IF+NOCS
# Using the intermediate feature of SegNet
# pretrained weights from full dataset

# DATASET_ROOT: '/workspace/Data/8_7_cut_BW_IF'
# DATASET_ROOT: '/workspace/Data/SAPIEN/eyeglasses/pose_aa_IF'
DATASET_ROOT: '/workspace/Data/SAPIEN/laptop/laptop_25_2000_IF'
OUTPUT_DIR: '/workspace/dev_nrnocs/output/laptop'

MODES: ['train','val']

BATCHSIZE: 1
DATALOADER_WORKERS: 1
EPOCH_TOTAL: 20

LR: 1e-4

SAVE_FREQ: 2
DATA_LIMIT: 100 
VAL_DATA_LIMIT: 1
IMAGE_SIZE: (320,240)
TARGETS: ["default"]
TASK: "lnrnet"
OUT_CHANNELS: 12 #4 + 1*8

# TEST_ON_TRAIN: True

MH: True
BN: False

NOCS_LOSS: 1
# POSE_LOSS: 1
# POSE_MAP_LOSS: 1
# LOC_LOSS: 1
# LOC_MAP_LOSS: 1
# SKIN_LOSS: 1

BONE_NUM: 1

# REPOSE: False
STAGE_ONE: True


# EXPT_NAME: "25inst_14"
EXPT_NAME: "25nox"

GPU: 5

